layers_index: map/layers/index.yaml
information:  map/information.yaml
locations:
  index:      map/locations/index.yaml
  pins:       map/locations/pins.yaml
  templates:  map/locations/templates.yaml